springfox:
 title: 'FINT Test Runner'
 version: '@version@'

server:
 port: 8083

fint:
 oauth:
  enabled: true
  access-token-uri: https://idp.felleskomponent.no/nidp/oauth/nam/token
  scope: fint-client



