apiVersion: fintlabs.no/v1alpha1
kind: Application
metadata:
  name: fint-test-runner
  namespace: fintlabs-no
  labels:
    app.kubernetes.io/name: fint-test-runner
    app.kubernetes.io/instance: fint-test-runner_fintlabs_no
    app.kubernetes.io/version: latest
    app.kubernetes.io/component: backend
    app.kubernetes.io/part-of: fint-core
    fintlabs.no/team: core
    fintlabs.no/org-id: fintlabs.no
spec:
  port: 8080
  imagePullPolicy: Always
  orgId: fintlabs.no
  image: ghcr.io/fintlabs/fint-test-runner:latest
  url:
    hostname: kunde-beta.felleskomponent.no
    basePath: /test-runner
  ingress:
    enabled: true
    middlewares:
      - fint-test-runner-sso
  envFrom:
    - secretRef:
        name: fint-portal-user
  env:
    - name: JAVA_TOOL_OPTIONS
      value: '-XX:+ExitOnOutOfMemoryError -Xmx800M'
  resources:
    limits:
      memory: "1Gi"
      cpu: "1"
    requests:
      memory: "512Mi"
      cpu: "250m"
  restartPolicy: Always
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate: { maxSurge: 1, maxUnavailable: 0 }